telegraf:
  fullnameOverride: telegraf
  tplVersion: 2
  # ! use envFromSecret
  # ? https://github.com/influxdata/telegraf/blob/release-1.31/docs/CONFIGURATION.md#secret-store-secrets
  env:
    - name: INFLUXDB_TOKEN
      valueFrom:
        secretKeyRef:
          name: influxdb-auth
          key: admin-token
    - name: MQTT_USER
      valueFrom:
        secretKeyRef:
          name: esp-cluster-default-user
          key: username
    - name: MQTT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: esp-cluster-default-user
          key: password
  config:
    agent:
      interval: "1s"
      round_interval: true
      metric_batch_size: 1000
      metric_buffer_limit: 10000
      collection_jitter: "0s"
      flush_interval: "10s"
      flush_jitter: "0s"
      precision: ""
      debug: false
      quiet: false
      logfile: ""
      hostname: "$HOSTNAME"
      omit_hostname: false
    inputs:
      - statsd:
          service_address: ":8125"
          percentiles:
            - 50
            - 95
            - 99
          metric_separator: "_"
          allowed_pending_messages: 10000
          percentile_limit: 1000
      - mqtt_consumer:
          servers:
            - "tcp://esp-cluster:1883"
          username: "${MQTT_USER}"
          password: "${MQTT_PASSWORD}"
          topics:
            - "esp-queue/+/coordinates"
          data_format: "json_v2"
          # data_format: "json"
          json_v2:
            - measurement_name: coordinates
              object:
                - path: "@this"
                  field:
                    - path: "latitude"
                      rename: "latitude"
                    - path: longitude
                      rename: longitude

          topic_parsing:
            - topic: "esp-queue/+/coordinates"
              # measurement: "_/_/measurement"
              tags: "_/device/_"
              #fields: "_/_/_"
              # types:
              #   device: string

    outputs:
      - influxdb_v2:
          urls:
            - "http://influxdb"
          token: tokentoken # "${INFLUXDB_TOKEN}"
          organization: "influxdata"
          bucket: "default"
