apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "devices-operator.fullname" . }}-manager-role
  labels:
  {{- include "devices-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devices.pedge.io
  resources:
  - devices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devices.pedge.io
  resources:
  - devices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - devices.pedge.io
  resources:
  - devicesclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devices.pedge.io
  resources:
  - devicesclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - devices.pedge.io
  resources:
  - firmwares
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devices.pedge.io
  resources:
  - firmwares/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - minio.min.io
  resources:
  - tenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - permissions
  - queues
  - rabbitmqclusters
  - topicpermissions
  - users
  - vhosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - permissions
  - topicpermissions
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "devices-operator.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pedge-devices-operator
    app.kubernetes.io/part-of: pedge-devices-operator
  {{- include "devices-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "devices-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "devices-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'