apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devices-operator.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pedge-devices-operator
    app.kubernetes.io/part-of: pedge-devices-operator
  {{- include "devices-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}