{{- $password := (.Values.password | default (include "userPassword" (dict "name" .Release.Name "namespace" $.Release.Namespace))) -}}
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    checksum/password: "{{ $password | sha256sum }}"
spec:
  rabbitmqClusterReference:
    name: "{{ .Values.cluster.name }}"
  importCredentialsSecret:
    name: "{{ .Release.Name }}"
---
# TODO do NOT include the passwords in the helm operator / CR spec
# TODO also watch the secret for changes and update user.rabbitmq.com/metadata/annotations/checksum/password
apiVersion: v1
kind: Secret
metadata:
  {{- /* It seems the "-user-credentials" suffix is managed by the rabbitmq topology operator */}}
  name: "{{ .Release.Name }}-user-credentials"
type: Opaque
data:
  username: "{{ .Release.Name | b64enc | quote }}"
  password: "{{ $password | b64enc | quote }}"
  {{- if and (hasKey . "network") (hasKey .Values.network "gsm") (hasKey .Values.network.gsm "pin") }}
  gsm_pin: {{ printf "%v" .Values.network.gsm.pin | b64enc | quote }}
  {{- else }}
  gsm_pin: {{ "0000" | b64enc | quote }}
  {{- end }}

---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: "{{ .Release.Name }}"
spec:
  vhost: "/"
  userReference:
    name: "{{ .Release.Name }}"
  permissions:
    configure: "^mqtt-subscription-.*$"
    write: "^amq\\.topic$|^mqtt-subscription-.*$"
    read: "^amq\\.topic$|^mqtt-subscription-.*$"
  rabbitmqClusterReference:
    name: "{{ .Values.cluster.name }}"
---

apiVersion: rabbitmq.com/v1beta1
kind: TopicPermission
metadata:
  name: "{{ .Release.Name }}"
spec:
  vhost: "/"
  userReference:
    name: "{{ .Release.Name }}"
  permissions:
    exchange: "amq.topic"
{{- /* Allow to write to any sub-topic of the queue/device name */}}
    write: "^{{ .Values.queue.name }}\\.{{ .Release.Name }}\\..+$"
    # TODO restrict back to no writes
    read: "^{{ .Values.queue.name }}\\.{{ .Release.Name }}\\..+$"
    # read: "" # * Only allow to write, not read
  rabbitmqClusterReference:
    name: "{{ .Values.cluster.name }}"
---


