apiVersion: devices.pedge.io/v1alpha1
kind: DeviceClass
metadata:
  name: deviceclass-sample
spec:
  builder:
    image:
      repository: ghcr.io/plmercereau/pedge/firmware-builder-esp32
      tag: latest
      pullPolicy: Always
