apiVersion: devices.pedge.io/v1alpha1
kind: Firmware
metadata:
  labels:
    app.kubernetes.io/name: firmware
    app.kubernetes.io/instance: firmware-sample
    app.kubernetes.io/part-of: pedge-devices-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pedge-devices-operator
  name: firmware-sample
spec:
  builder:
    image:
      registry: ghcr.io
      repository: plmercereau/firmware-builder-esp32-sim7600
      tag: latest
      pullPolicy: Always
