apiVersion: devices.pedge.io/v1alpha1
kind: DevicesCluster
metadata:
  labels:
    app.kubernetes.io/name: devicescluster
    app.kubernetes.io/instance: devicescluster-sample
    app.kubernetes.io/part-of: pedge-devices-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pedge-devices-operator
  name: devices-cluster
spec:
  mqtt:
    sensorsTopic: sensors
  influxdb:
    name: influxdb
    namespace: default
    secretReference:
      name: influxdb-auth
