apiVersion: devices.pedge.io/v1alpha1
kind: DeviceCluster
metadata:
  name: my-cluster
spec:
  artefacts:
    image:
      repository: ghcr.io/plmercereau/pedge/firmware-artefacts
      tag: latest
    ingress:
      enabled: true
      hostname: devices.local
  mqtt:
    # hostname: mqtt.example.com
    # port: 1883
    sensorsTopic: sensors
    users:
      - name: device-listener
        role: reader
        injectSecrets:
          - name: influxdb-auth
            namespace: default
            mapping:
              brokerUrl: MQTT_BROKER_URL
              username: MQTT_USERNAME
              password: MQTT_PASSWORD
              sensorsTopic: MQTT_TOPIC_SENSORS
            # Add reloader.stakater.com/match: "true" to the secret to trigger a reload of the telegraf config
            annotations:
              "reloader.stakater.com/match": "true"
