apiVersion: devices.pedge.io/v1alpha1
kind: DevicesCluster
metadata:
  name: my-cluster
spec:
  mqtt:
    sensorsTopic: sensors
  influxdb:
    # name: influxdb
    namespace: default
    secretReference:
      name: influxdb-auth
