apiVersion: devices.pedge.io/v1alpha1
kind: DeviceClass
metadata:
  name: esp32cam
spec:
  devicesClusterReference:
    name: my-cluster
  builder:
    image:
      repository: ghcr.io/plmercereau/pedge/firmware-builder-esp32
      tag: latest
      pullPolicy: IfNotPresent
    env:
      - name: TARGET
        value: esp32cam
  config:
    image:
      repository: ghcr.io/plmercereau/pedge/config-builder-esp32
      tag: latest
      pullPolicy: IfNotPresent
