resources:
  - devicecluster.yaml
  - devicecluster-secret.yaml
  - deviceclass_esp32cam.yaml
  - device_esp32cam.yaml
  - esp32cam-user-credentials.yaml
secretGenerator:
  - name: my-cluster-device-cluster
    envs:
      - .cluster.env
    behavior: merge
