apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="minio"
    export MINIO_ROOT_PASSWORD="minio123"
    export MINIO_STORAGE_CLASS_STANDARD="EC:2"
    export MINIO_BROWSER="on"

---
apiVersion: v1
kind: Secret
metadata:
  name: storage-user
type: Opaque
stringData:
  CONSOLE_ACCESS_KEY: console
  CONSOLE_SECRET_KEY: console123

---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: storage
spec:
  users:
    - name: storage-user
  configuration:
    name: storage-configuration
  pools:
    - servers: 4
      name: minio-pool-default
      volumesPerServer: 4
      volumeClaimTemplate:
        apiVersion: v1
        kind: persistentvolumeclaims
        metadata: {}
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
  buckets:
    - name: firmwares
      region: default
      objectLocking: false
  requestAutoCert: true
