apiVersion: v1
kind: PersistentVolume
metadata:
  name: devices
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /data
    type: ""
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devices
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
