# permissions for end users to view firmwares.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: firmware-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pedge-devices
    app.kubernetes.io/part-of: pedge-devices
    app.kubernetes.io/managed-by: kustomize
  name: firmware-viewer-role
rules:
- apiGroups:
  - devices.pedge.io
  resources:
  - firmwares
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devices.pedge.io
  resources:
  - firmwares/status
  verbs:
  - get
