- op: add
  path: /rules/-
  value:
    apiGroups: ["devices.pedge.io"]
    resources: ["telegrafs"]
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
