# - op: add
#   path: /rules/-
#   value:
#     apiGroups: ["devices.pedge.io"]
#     resources: ["helm-crd-plural-name"]
#     verbs:
#       - create
#       - delete
#       - get
#       - list
#       - patch
#       - update
#       - watch
