grafana:
  enabled: true
  fullnameOverride: grafana
  ingress:
    enabled: true
    ingressClassName: traefik
  # Initial admin/password
  admin:
    user: admin
    password: admin
  datasources:
    secretName: grafana-datasources
  grafana:
    extraEnvVars:
      - name: INFLUXDB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: influxdb-auth
            key: admin-password
      - name: INFLUXDB_TOKEN
        valueFrom:
          secretKeyRef:
            name: influxdb-auth
            key: admin-token

influxdb:
  enabled: true
  fullnameOverride: influxdb
  adminUser:
    organization: "influxdata"
    bucket: "default"
    user: "admin"
    password: adminadmin
    token: tokentoken

telegraf:
  enabled: true
  fullnameOverride: telegraf
  tplVersion: 2
  # TODO telegraf should restart if the secret changes
  # TODO put telegraf into the operator...
  envFromSecret: device-listener-user-credentials # ! This is the only way to connect to the operator-managed devices cluster
  # ? https://github.com/influxdata/telegraf/blob/release-1.31/docs/CONFIGURATION.md#secret-store-secrets
  env:
    - name: INFLUXDB_TOKEN
      valueFrom:
        secretKeyRef:
          name: influxdb-auth
          key: admin-token

  config:
    agent:
      interval: "1s"
      round_interval: true
      metric_batch_size: 1000
      metric_buffer_limit: 10000
      collection_jitter: "0s"
      flush_interval: "10s"
      flush_jitter: "0s"
      precision: ""
      debug: false
      quiet: false
      logfile: ""
      hostname: "$HOSTNAME"
      omit_hostname: false
    inputs:
      - statsd: # TODO I do not want this input
          service_address: ":8125"
          percentiles:
            - 50
            - 95
            - 99
          metric_separator: "_"
          allowed_pending_messages: 10000
          percentile_limit: 1000
      - mqtt_consumer:
          servers:
            - "${MQTT_URL}"
          username: "${username}"
          password: "${password}"
          topics:
            - "${MQTT_TOPIC}/+/coordinates"
          data_format: "json_v2"
          json_v2:
            - measurement_name: coordinates
              object:
                - path: "@this"
                  field:
                    - path: "latitude"
                      rename: "latitude"
                    - path: longitude
                      rename: longitude

          topic_parsing:
            - topic: "${MQTT_TOPIC}/+/coordinates"
              # measurement: "_/_/measurement"
              tags: "_/device/_"
              #fields: "_/_/_"
              # types:
              #   device: string

    outputs:
      - influxdb_v2:
          # TODO in configmap
          urls:
            - "http://influxdb"
          token: "${INFLUXDB_TOKEN}" # TODO make it works
          organization: "influxdata"
          bucket: "default"
