apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: "[]"
    capabilities: Basic Install
  name: pedge-devices-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: Device is the Schema for the devices API
        displayName: Device
        kind: Device
        name: devices.devices.pedge.io
        version: v1alpha1
  description: An operator for managing a cluster of MCU devices and sensors
  displayName: pedge-devices-operator
  icon:
    - base64data: ""
      mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
    - supported: false
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - mcu
    - mqtt
  links:
    - name: Operator Test
      url: https://pedge-devices-operator.domain
  maturity: alpha
  provider:
    name: pedge-devices-provider
  version: 0.0.0
