apiVersion: devices.pedge.io/v1alpha1
kind: Device
metadata:
  labels:
    app.kubernetes.io/name: device
    app.kubernetes.io/instance: device-sample
    app.kubernetes.io/part-of: pedge-devices-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pedge-devices-operator
  name: device-sample
spec:
  mqttServerReference:
    name: esp-cluster
  firmwareReference:
    name: firmware-sample
