apiVersion: v2
name: devices-operator
description: A Helm chart for installing the devices operator.
type: application
version: 0.0.0
appVersion: 0.0.0
dependencies:
  - name: rabbitmq-cluster-operator
    alias: rabbitmq-operator
    version: 4.2.10
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: rabbitmq-operator.enabled
  - name: operator
    alias: minio-operator
    version: 5.0.15
    repository: https://operator.min.io
    condition: minio-operator.enabled
