replicaCount: 1

image:
  repository: ghcr.io/plmercereau/pedge/devices-operator
  # Use the chart appVersion as the default tag
  # tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

fullNameOverride: ""

rabbitmq-operator:
  enabled: false
  fullnameOverride: rabbitmq-cluster-operator
  useCertManager: true

minio-operator:
  enabled: false
  fullnameOverride: minio-operator
