name: Build and Push Multi-Platform Docker Images

on:
  push:
    branches:
      - main

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Parse versions.yaml
        id: parse_yaml
        uses: mikefarah/yq@v4
        with:
          cmd: cat versions.yaml
          output: json

      - id: set-matrix
        run: |
          matrix=$(echo '${{ steps.parse_yaml.outputs.result }}' | jq -c 'to_entries | map({context: .key, name: .value.name, version: .value.version})')
          echo "matrix=$matrix" >> $GITHUB_ENV

  build-and-push:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.name }}:${{ matrix.version }}
            ghcr.io/${{ github.repository }}/${{ matrix.name }}:latest
          push: true
