# TODO Readme on docker hub / ghcr.io
name: Build and Publish artefacts

on:
  push:
    branches:
      - main

jobs:
  generate-matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.set-matrix.outputs.images }}
      charts: ${{ steps.set-matrix.outputs.charts }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Parse versions.yaml
        id: set-matrix
        run: |
          images=$(yq -o=json '[.[] | select(has("dockerContext"))]' versions.yaml -I 0)
          echo "images=$images" >> "$GITHUB_OUTPUT"
          charts=$(yq -o=json '[.[] | select(has("helmContext"))]' versions.yaml -I 0)
          echo "charts=$charts" >> "$GITHUB_OUTPUT"

  build-and-push-images:
    needs: generate-matrix
    runs-on: ubuntu-latest
    name: "Image: ${{ matrix.name }}"
    strategy:
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.images) }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        id: push
        with:
          context: ${{ matrix.dockerContext }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}:${{ matrix.version }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}:latest
            plmercereau/${{ matrix.name }}:${{ matrix.version }}
            plmercereau/${{ matrix.name }}:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  publish-charts:
    needs:
      - generate-matrix
      # TODO add the dependency again
      # - build-and-push-images
    runs-on: ubuntu-latest
    name: "Chart: ${{ matrix.name }}"
    strategy:
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.charts) }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: test
        run: |
          echo "test"
          echo ${{ matrix.helmContext }}
      # # TODO helm repo add / search not supported: https://github.com/apollographql/router/issues/1643
      # # TODO fall back to curl...
      # - name: Connect helm to the ghcr.io registry
      #   run: |
      #     helm registry login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      # - name: add the OCI ghcr.io repository plmercereau/pedge
      #   run: |
      #     helm repo add plmercereau oci://ghcr.io/plmercereau/pedge
      #     helm repo update
      # - name: get latest helm version and put it into an output so it can be used in the next step
      #   id: get_latest_version
      #   run: |
      #     VERSION=$(helm search repo -r "\vbitnami/nginx\v" -o json | jq -r '.[0].version')
      #     echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      # - name: Echo the latest helm version from previous step
      #   run: |
      #     echo ${{ steps.get_latest_version.outputs.latest_version }}
