name: Buil ESP-Monitor Image

on:
  # pull_request:
  push:
    branches: [main]

env:
  image_name: esp-monitor

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Build image
        run: nix build .\#${{ env.image_name }}
      - name: Load Docker image
        run: docker load < result
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Tag Docker image
      #   run: |
      #     docker tag ${{ env.image_name }}:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.image_name }}:${{ github.sha }}
      - name: Push Docker image
        run: docker push --all-tags $(nix eval .\#${{ env.image_name }}.imageName | jq -r)
